### ISSUE TITLE
Provide JS and CSS files as part of the release

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/product-kit_core#18]
Provide the JS and CSS files as part of a release. Provide the files as minified version as well.

As far as understood, those files are enough to use actually use the `product-kit_core`.
This would mean this code would be enough to use the `product-kit_core`:

~~~html
<!DOCTYPE html>
<html>

<head>
    <title>My page</title>
    <link rel="stylesheet" type="text/css" href="variables.css" />
    <style>
        body {
            background: var(--color-brand-deepblue-900);
            color: var(--color-brand-deepblue-contrast-900);
        }
    </style>
</head>

<body>
    <h1>My page</h1>
    <p>My own page..</p>
</body>

</html>
~~~

The output will look like this:

![image](https://user-images.githubusercontent.com/2007739/168832623-0ab99778-57ee-421f-b4fa-87c272233e4a.png)

The JS and CSS files would be enough to get started using the `product-kit_core` even in scenarios where one does not need or want to use NodeJS and NPM.

**Comment by stenanderssen** [comment]
Hi @Jeeppler 
Sorry for the late reply. We will provide an additional minified version of the css version in the dist directory of Product Kit Core with the next minor release. We won't provide any additional assets in the Github release because we don't see any additional value in contrast to just download the file from the source directory. We also don't want to encourage users to download the files without a package/dependency manager. 

See #28
